# Uncomment the next line to define a global platform for your project
platform :ios, ‘9.2’

target 'PortfolioRedondo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PortfolioRedondo

	pod ‘Firebase/Core’ , ’5.6.0’
	pod ‘Firebase/Firestore’ , ‘5.6.0’
	pod 'SwiftyJSON' , ‘4.0.0’
	pod 'Alamofire’, ‘4.5.1’
	pod 'SVProgressHUD'
	pod ‘ZKCarousel’

end
